apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-gateway
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: taiga-gateway
spec:
  ports:
    - name: http
      port: {{ .Values.taigaGateway.service.port }}
      targetPort: http
  type: {{ .Values.taigaGateway.service.type }}
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: taiga-gateway
